### ISSUE TITLE
Add ability to customize maxRetryCount

### ISSUE THREAD

**Issue by techthumb** [sterlp/pmw#4]
Hi @sterlp,

I want to override the the default `maxRetryCount` at https://github.com/sterlp/pmw/blob/v1.1.1/core/src/main/java/org/sterl/pmw/model/AbstractStep.java#L17

How do you feel about making this method `public`?
https://github.com/sterlp/pmw/blob/v1.1.1/core/src/main/java/org/sterl/pmw/model/AbstractWorkflowFactory.java#L11

This would allow the client add their own `step` whilst not cluttering the builder with every customizable option.

**Comment by sterlp** [comment]
somehow the setter is missing here. Making the add public makes sense too me; do you want to add a PR?

**Comment by sterlp** [comment]
released v1.2.1

**Comment by techthumb** [comment]
Thank you!
